# Generated by Django 4.1.2 on 2022-11-23 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_rename_smsmessage_notificationmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationMessage',
        ),
    ]
