# Generated by Django 4.1.2 on 2022-11-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmessage',
            name='driver_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
