# Generated by Django 4.1.2 on 2022-11-13 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('dealership_affiliations', models.JSONField(blank=True, null=True)),
                ('location', models.JSONField(blank=True, null=True)),
                ('postal_address', models.CharField(blank=True, max_length=255, null=True)),
                ('town', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('subscription', models.CharField(choices=[('paid', 'Paid'), ('freemium', 'Freemium')], default='freemium', max_length=255)),
                ('subscription_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('pricing_type', models.CharField(choices=[('negotiable', 'Negotiable'), ('not_negotiable', 'Not Negotiable')], max_length=255)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='garages.garage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GarageSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('payment_method', models.CharField(choices=[('mpesa', 'Mpesa'), ('cash', 'Cash'), ('card', 'Card')], default='mpesa', max_length=255)),
                ('payment', models.JSONField(blank=True, null=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='garages.garage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
