# Generated by Django 4.1.2 on 2022-11-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0005_garageowner_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='location_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='garage',
            name='year_opened',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
