# Generated by Django 4.1.2 on 2022-11-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carbrand_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], max_length=255),
        ),
    ]
