# Generated by Django 4.1.2 on 2022-11-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_smsmessage_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessage',
            name='notification_type',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=255),
        ),
    ]
